### ISSUE TITLE
卡在支付界面之前

### ISSUE THREAD

**Issue by q1nwu** [838239178/damai_tickets#4]
您好，启动程序，总是卡在支付界面之前，麻烦解答，感谢

**Comment by huangAoJiong** [comment]
我是卡在选日期那里，麻烦说说你的config.json怎么写的感谢感谢

**Comment by q1nwu** [comment]
> 我是卡在选日期那里，麻烦说说你的config.json怎么写的感谢感谢

我用的默认的config～

**Comment by saddit** [comment]
配置文件发出来看看

**Comment by q1nwu** [comment]
> 配置文件发出来看看

使用默认config.json。仔细看了下，页面卡在无法自动勾选 观演人。 感谢回复

**Comment by wuliang9524** [comment]
capa["pageLoadStrategy"] = "eager"
self.driver = webdriver.Chrome(
            executable_path=self.driver_path, options=options, desired_capabilities=capa)

等待策略这里更换为 等待 DOM 节点加载完毕再进行会好一点,不然很容易获取不到重要的 DOM 节点导致抛出异常

**Comment by q1nwu** [comment]
> capa["pageLoadStrategy"] = "eager" self.driver = webdriver.Chrome( executable_path=self.driver_path, options=options, desired_capabilities=capa)
> 
> 等待策略这里更换为 等待 DOM 节点加载完毕再进行会好一点,不然很容易获取不到重要的 DOM 节点导致抛出异常


> capa["pageLoadStrategy"] = "eager" self.driver = webdriver.Chrome( executable_path=self.driver_path, options=options, desired_capabilities=capa)
> 
> 等待策略这里更换为 等待 DOM 节点加载完毕再进行会好一点,不然很容易获取不到重要的 DOM 节点导致抛出异常

感谢回复，我试试

**Comment by MengHaodong1** [comment]
周杰伦门票没抢到

**Comment by MengHaodong1** [comment]
###进入抢票界面###
###等待跳转到--付款界面--，可自行刷新，若长期不跳转可选择-- CRTL+C --重新抢票###
Traceback (most recent call last):
  File "D:\python_project\damai_tickets\main.py", line 272, in check_order
    WebDriverWait(self.driver, 3600, 0.1).until(
  File "D:\python_project\damai_tickets\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "D:\python_project\damai_tickets\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 55, in _predicate
    return title in driver.title
  File "D:\python_project\damai_tickets\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 460, in title
    return self.execute(Command.GET_TITLE).get("value", "")
  File "D:\python_project\damai_tickets\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\python_project\damai_tickets\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=111.0.5563.147)
Stacktrace:
Backtrace:
	(No symbol) [0x0022E073]
	(No symbol) [0x001C39F1]
	(No symbol) [0x000D4FF8]


请问这是什么问题呢
